mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings


# The URLs that can be accessed.
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/wiki/urls.py
from django.urls import path, include

from . import views

app_name = 'wiki'

# The URLs that the user will be able to access.
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), 
    path('download/uploads/<str:path>/', views.download_file, name='download'),
    path('upload/', views.upload_file, name='upload_page' ),
    path('<str:pk>/edit', views.edit_page, name='edit_page'),
    path('<str:pk>/save', views.save_page, name='save_page'),
    path('<str:pk>/', views.view_page, name='detail'),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/wiki/models.py
from django.db import models
from django.urls import reverse

# Models are classes that make up the webpages in this server.

class Page(models.Model):
    title = models.CharField(max_length=64, primary_key=True)
    content = models.TextField()
    counter = models.IntegerField(default = 1)
    def __str__(self):
        return self.title
    
    # This redirects the user to the page that they have requested, retrieves and ooutputs content accordingly.
    def get_absolute_url(self):
        return reverse('wiki:detail', args=[self.title])

class UserFileUpload(models.Model):
    upload = models.FileField(upload_to='uploads/')
    #file will be saved to MEDIA_ROOT/uploads

    def __str__(self):
        return self.upload.name

mysite/wiki/forms.py
from django.forms import ModelForm
from .models import UserFileUpload

# In order to accept files submitted by users, forms must be used.
class UploadFileForm(ModelForm):
    class Meta:
        model = UserFileUpload
        fields = ['upload' ]

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
        pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/wiki/views.py
from django.views import generic
from .models import Page, UserFileUpload
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UploadFileForm
import logging
from django.db.models import F
import os
from django.conf import settings
from django.http import HttpResponse, Http404

# Get an instance of a logger which helps us keep a log of pages that are requested.
logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    template_name = 'wiki/index.html'
    context_object_name = 'pages'
    def get_queryset(self):
        return Page.objects.all()
    
    
class DetailView(generic.DetailView):
    model = Page
    template_name = 'wiki/detail.html'


def view_page(request, pk): # Gives the ability to view pages.
    try:
        page = Page.objects.get(pk=pk)
        page.counter = F('counter') + 1
        page.save(update_fields=['counter'])
        page.refresh_from_db()
        return render(request, 'wiki/detail.html', {'page': page})
    except Page.DoesNotExist:
        return render(request, 'wiki/create_page.html', {'page_name': pk})

@login_required(login_url='wiki:login') # If logged out, redirects the user to the login screen.
def edit_page(request, pk):
    try:
        page = Page.objects.get(pk=pk)
        content = page.content
    except Page.DoesNotExist:
        content=''
    return render(request, 'wiki/edit_page.html',{ 'page_name':pk, 'content':content},)

def save_page(request, pk): # Gives the abiliy to save pages.
    content = request.POST["content"]
    try:
        page = Page.objects.get(pk=pk)
        page.content = content
    except Page.DoesNotExist:
        page = Page(title=pk, content=content)
    if 'Save' in request.POST:
        page.save()
    return redirect(page)

@login_required(login_url='wiki:login') # If logged out when trying to access File Upload, redirects the user to the login screen.
def upload_file(request):
    context = {}
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = UploadFileForm()
    context['form'] = form
    context['files'] = UserFileUpload.objects.all().order_by('upload')
    return render(request, 'wiki/upload.html', context)

@login_required(login_url='wiki:login') # If logged out when trying to download a file, redirects the user to the login screen.
def download_file(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT + '/uploads', path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

def my_view(request, arg1, arg):
    if bad_mojo:
        # Log an error message
        logger.error('Something went wrong!')

mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
{% block content %}NO CONTENT PROVIDED{% endblock content %}
</body>
</html>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
<h2>{{ title }}</h2>
<div class="container">
{% if latest_question_list %}

    <ul class="list-group">
    {% for question in latest_question_list %}
    <li class="list-group-item"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
{% endblock content %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/wiki/templates/wiki/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/wikistyle.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">

</head>

<div class="container" style="margin-top:20px;">
    <h1 style="display:inline">Vikipidia</h1> 
    <!-- Spinners -->
    <div class="spinner-grow" id="spinner1" role="status" style="animation-delay: 0s; animation-duration: 4s;">
    </div>
    <div class="spinner-grow" id="spinner2" role="status" style="animation-delay: 4s; animation-duration: 4s;">
    </div>
    <div class="spinner-grow" id="spinner3" role="status" style="animation-delay: 8s; animation-duration: 4s;">
    </div>
    <div class="spinner-grow" id="spinner4" role="status" style="animation-delay: 12s; animation-duration: 4s;">
    </div>
    <div class="spinner-grow" id="spinner5" role="status" style="animation-delay: 16s; animation-duration: 4s;">
    </div>
    <div class="spinner-grow" id="spinner6" role="status" style="animation-delay: 20s; animation-duration: 4s;">
    </div>
    <div class="spinner-grow" id="spinner7" role="status" style="animation-delay: 24s; animation-duration: 4s;">
    </div>
    <div class="spinner-grow" id="spinner8" role="status" style="animation-delay: 28s; animation-duration: 4s;">
    </div>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light justify-content-start ml-auto">
        <a class="nav-link" href="{% url 'wiki:index' %}">Homepage</a> 
        <a class="nav-link" href="{% url 'wiki:upload_page' %}">File Upload</a>

        <!-- Logout / Login buttons -->
        <div class="justify-content-end ml-auto">
            {% if user.is_authenticated%}
            <a class="btn btn-lg" id="logoutbase" style="padding:10px 20px 10px 10px"
                href="{% url 'wiki:logout'%}">Logout</a> 
            {% else %}
            <a class="btn btn-lg" style="margin-left:auto; float:right !important;" id="loginbase"
                href="{% url 'wiki:login' %}">Go to Login</a>
            {% endif %}
        </div>
    </nav>
</div>
<hr />

<body>
    {% block content %}NO CONTENT PROVIDED{% endblock content %}
</body>

</html>

mysite/wiki/templates/wiki/create_page.html
{% extends "wiki/base.html" %} <!-- The base.html is displayed first -->
{% block content %}
{% block contentTitle %}
<div class="container">
    <h2>{{page_name}}</h2>{% endblock %} <!-- Name of the Page -->
    <h5>There is no content for this page.</h5>
    <a class="btn" id="createpagebutton" href="{% url 'wiki:edit_page' page_name %}">Create a page named
        {{page_name}}</a> <!-- Button that redirects the user to editing the new page -->
    <a class="btn" id="indexbutton" href="{%url 'wiki:index' %}">Index</a> <!-- Index / Homepage button --> 
</div>
{% endblock %}

mysite/wiki/templates/wiki/detail.html
{% extends 'wiki/base.html' %} <!-- The base.html is displayed first -->
{% load wiki_tags %} <!-- Loads wiki_tags.py  -->
{% block content %}
<div class="container">
    {% block contentTitle %}
    <h2 class="text-primary">{{page.title}}</h2>
    {% endblock %}
    <hr />
    {{page.content|markup|wikify|safe}} <!-- The markup and wikify are defined in wiki_tags.py. The safe marks a string as not requiring further HTML escaping prior to output. --> 
    <hr />
    <div>
        <a class="btn btn-lg" id="indexbutton" href="{% url 'wiki:index' %}">Index</a> <!-- Index / Homepage button -->
        <a class="btn btn-lg" id="editbutton" href="{% url 'wiki:edit_page' page.title %}">Edit</a> <!-- Edit button -->
    </div>
    This page has been visited {{ page.counter }} times. <!-- Shows how many times the page has been visited. -->   
</div>
{% endblock content %}

mysite/wiki/templates/wiki/edit_page.html
{% extends 'wiki/base.html' %} <!-- The base.html is displayed first -->
{% load staticfiles %} 
{% block pageheader %}Editing {{ page_name }}{% endblock %} {% block content %}
<div class="container">
    {% block contentTitle %}
    <h3>You are now editing the wiki page known as:</h3>
    <h4>
        <i>{{page_name}}</i>
    </h4>
    {% endblock %}
    <br />
    <!-- Notifies the user that Markdown is compatible and provides a Markdown cheatsheet. -->
    <h6>
        <strong>Markdown</strong> is compatible with this text editor and it is recommended. You can also drag the text editor downwards
        by grabbing the bottom right corner of the text editor, if more space is needed.</h6>
    <h6>Here is a
        <strong>
            <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown Cheatsheet</a>
        </strong> if you are new to Markdown.</h6>
    <form method="post" action="{% url 'wiki:save_page' page_name %}">
        {% csrf_token %}
        <textarea id="id_content" name="content" rows="10" cols="120">{{content}}</textarea> <!-- Where the user writes the content, the text area -->
        <input class="btn" id="savebutton" name="Save" type="submit" value="Save"> <!-- Save button -->
        <input class="btn" id="cancelbutton" name="Cancel" type="submit" value="Cancel"> <!-- Cancel button -->
    </form>
</div>
{% endblock %}

mysite/wiki/templates/wiki/index.html
{% extends "wiki/base.html" %} {% load static %} {% block content %} {% block title %} {% endblock %}
<div class="container">
    <!-- Displaying appropriate welcoming messages for users and guests. -->
    {% if user.is_authenticated %} 
    <h2>Welcome to Vikipidia, {{ request.user.username }}!</h2>    
    <h6>You are browsing from {{ request.META.HTTP_USER_AGENT }}, and your IP is {{ request.META.REMOTE_ADDR }}.</h6> 
    {% else %} 
    <h2>Welcome to Vikipidia, Guest!</h2>
    <h6>You are browsing from {{ request.META.HTTP_USER_AGENT }}, and your IP is {{ request.META.REMOTE_ADDR }}.</h6> 
    {% endif %}
    <!-- Screen resolution function -->
    <a onclick="myFunction()" id="demo" style="color:rgb(20, 100, 53)">Click here to find out your screen
        resolution!</a>
    <hr />
    <!-- How to create a new page -->
    <h5>To create a new page, simply click after the 'wiki/' bit on the search bar at the top, and type in the name of
        your desired page.</h5>
    <h6>Below are the pages that have been already created. It is possible to create new pages and edit existing ones,
        however you must be logged in.</h6>
    <!-- If there are pages, display them as a list -->
        {% if pages %}
    <ul class="list-group">
        {% for page in pages %}
        <li class="list-group-item list-group-item-action">
            <a href="{% url 'wiki:detail' page.title %}">{{ page.title }}</a>
        </li>
        {% endfor %}
    </ul>
    <!-- If there aren't any, display the paragraph -->
    {% else %}
    <p>No pages are available at this time.</p>
    {% endif %}
</div>
<script>
    /* Screen resolution function */
    function myFunction() {
        var x = "Your screen resolution is: " + screen.width + "x" + screen.height + " (" + screen.width + " pixels wide and " + screen.height + " pixels tall)";
        document.getElementById("demo").innerHTML = x;
    }
</script>

{% endblock content %}

mysite/wiki/templates/wiki/upload.html
{% extends 'wiki/base.html' %} <!-- The base.html is displayed first -->
{% load static %} 
{% block content %}
<div class="container">
    {% block contentTitle %}
    <h2>File Upload</h2>{% endblock %}
    <!-- Explanatory Text -->
    <h6>On this part of the wiki, you can upload files, check the files that were uploaded and the most important - that's if
        you intend to edit pages and include images - is the corresponding file directory for the image you want to include
        in the edited page.</h6>
    <!-- Form which lets the user choose a file and upload it -->    
    <form method='POST' enctype='multipart/form-data' action="{% url 'wiki:upload_page' %}">
        {% csrf_token %} {{form}}
        <input type='submit' id="uploadbutton" value="Upload">
    </form>
    <section>
        <hr /> {% if files %}
        <!-- The list of stored files, along with a Download button for each one -->
        <table class="table table-hover" colspan="2" width="100%">
            <thead>
                <tr>
                    <th scope="col" width="60%" class="text-center border">File</th>
                    <th scope="col" width="40%" class="text-center border">Download</th>
                </tr>
            </thead>
            {% for file in files %}
            <tr>
                <td width="60%" class="border">
                    <a href="{{file.upload.url}}">{{file.upload.name}}</a>
                </td>
                <td width="40%" class="text-center border">
                    <a href="/download/{{file}}">Click to Download</a>
                </td>
            </tr>
            {% endfor %} {% else %}
            <p>No uploaded files</p>
            {% endif %}
        </table>
    </section>
</div>
{% endblock %}